language: node_js

services:
    -docker

#Pretesting Installs
 install:
    -echo "nothing needs to be installed"

 #Scripts to be run such as tests
 before_script:
    -echo "no tests"

 script:
   -echo pwd
   -docker --version
   -docker build -t "$DOCKER_USER"/udagram-user:prod ./udagram-mirco-api-user
   -docker build -t "$DOCKER_USER"/udagram-feed:prod ./udagram-micro-api-feed
   -docker build -t "$DOCKER_USER"/udagram-frontend:prod ./udagram-mirco-frontend


after_success:
  -echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password stdin
  -docker push "$DOCKER_USER"/udagram-frontend:prod
  -docker push "$DOCKER_USER"/udagram-user:prod
  -docker push "$DOCKER_USER"/udagram-feed:prod
