language: node_js
node_js:
  - 13

services:
  - docker

script:
  - echo pwd
  - docker --version
  - cd $TRAVIS_BUILD_DIR
  - ls -a
  - cd $TRAVIS_BUILD_DIR/udagram-micro-api-user
  - docker build -t "$DOCKER_USER"/udagram-user:prod .
  - cd $TRAVIS_BUILD_DIR/udagram-micro-api-feed
  - docker build -t "$DOCKER_USER"/udagram-feed:prod .
  - cd $TRAVIS_BUILD_DIR/udagram-micro-frontend
  - docker build -t "$DOCKER_USER"/udagram-frontend:prod .
  - cd $TRAVIS_BUILD_DIR/udagram-micro-deployment/docker
  - docker build -t "$DOCKER_USER"/udagram-reverseproxy:prod .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
  - docker push "$DOCKER_USER"/udagram-frontend:prod
  - docker push "$DOCKER_USER"/udagram-user:prod
  - docker push "$DOCKER_USER"/udagram-feed:prod
  - docker push "$DOCKER_USER"/udagram-reverseproxy:prod
