language: node_js
node_js:
  - 13

services:
  - docker

#Pretesting Installs
install:
 - echo "nothing needs to be installed"

 #Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - echo pwd
  - docker --version
  - cd $TRAVIS_BUILD_DIR/udagram-mirco-api-user
  - docker build -t "$DOCKER_USER"/udagram-user:prod .
  - cd $TRAVIS_BUILD_DIR/udagram-micro-api-feed
  - docker build -t "$DOCKER_USER"/udagram-feed:prod .
  - cd $TRAVIS_BUILD_DIR/udagram-mirco-frontend
  - docker build -t "$DOCKER_USER"/udagram-frontend:prod .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password stdin
  - docker push "$DOCKER_USER"/udagram-frontend:prod
  - docker push "$DOCKER_USER"/udagram-user:prod
  - docker push "$DOCKER_USER"/udagram-feed:prod
